export const ACCESS_TOKEN = 'accessToken'
export const LOGIN_PAGE = '/login/'
export const INVALID_CREDIT = 'auth/invalid-login-credentials'
export const PROJECT_PAGE = '/project'
export const OPTION_PAGE = '/option'
export const DEMO_PAGE = '/demo'
export const DEPLOYER_PAGE = '/deployer'
export const ADMIN_PAGE = '/admin'
export const CONVERSATION_DATA_PAGE = '/conversation'
export const CATEGORY_PAGE = '/category'
export const SKYPE_USER_PAGE = '/skypeUser'
export const TAG_PAGE = '/tag'
export const COMMAND_PAGE = '/command'
export const MEMBER_PAGE = '/member'
export const MENU_PAGE = '/menu'
export const ORDER_PAGE = '/order'
export const TRANSACTION_PAGE = '/transaction'

//API Endpoint
export const CHECK_USER_EXISTED_END_POINT = '/users/checkUserExisted'
export const GET_RECOVERY_KEY_END_POINT = '/users/e2ee-keys'
export const REGISTER_USER_END_POINT = '/users/register'
export const GET_USER_CHAT_ROOMS_END_POINT = '/rooms'
export const SEARCH_CONVERSATION_END_POINT = '/rooms/search'
export const GET_DIRECT_CHAT_END_POINT = '/rooms/direct'

//CONSTANT
export const PRIVATE_KEY_PAIR_KEY = 'e2ee-private-key'
